import { FontAwesomeIcon, type FontAwesomeIconProps } from '@fortawesome/react-fontawesome';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faBars,
  faBook,
  faBookOpen,
  faCalendarDays,
  faCommentDots,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleQuestion,
  faClock,
  faCloudArrowUp,
  faDownload,
  faEllipsis,
  faEye,
  faEyeSlash,
  faFileArrowUp,
  faFileLines,
  faFloppyDisk,
  faFolderOpen,
  faFolderTree,
  faGear,
  faGlobe,
  faLayerGroup,
  faLink,
  faListCheck,
  faMagnifyingGlass,
  faMoon,
  faMusic,
  faPause,
  faPenToSquare,
  faPlay,
  faPlus,
  faRotate,
  faShieldHalved,
  faShareNodes,
  faSpinner,
  faSquare,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUserCheck,
  faUserPlus,
  faUsers,
  faVolumeHigh,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { faCirclePause, faCirclePlay } from '@fortawesome/free-regular-svg-icons';
import { faGoogleDrive } from '@fortawesome/free-brands-svg-icons';

export const appIcons = {
  add: faPlus,
  back: faArrowLeft,
  batch: faFileLines,
  book: faBook,
  bookOpen: faBookOpen,
  calendar: faCalendarDays,
  check: faCheck,
  checkCircle: faCircleCheck,
  comment: faCommentDots,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  close: faXmark,
  contentUpdate: faFolderTree,
  crawl: faPlus,
  crawlHistory: faFileLines,
  dashboardUsers: faUsers,
  delete: faTrash,
  download: faDownload,
  drag: faEllipsis,
  edit: faPenToSquare,
  empty: faCircleCheck,
  error: faCircleExclamation,
  external: faArrowRight,
  file: faFileLines,
  folder: faFolderOpen,
  globe: faGlobe,
  info: faCircleInfo,
  link: faLink,
  list: faLayerGroup,
  logout: faArrowRightFromBracket,
  menu: faBars,
  pause: faPause,
  pauseCircle: faCirclePause,
  play: faPlay,
  playCircle: faCirclePlay,
  question: faCircleQuestion,
  refresh: faRotate,
  save: faFloppyDisk,
  search: faMagnifyingGlass,
  settings: faGear,
  share: faShareNodes,
  shield: faShieldHalved,
  speaker: faVolumeHigh,
  spinner: faSpinner,
  statusWarning: faTriangleExclamation,
  stop: faSquare,
  supportedSites: faGlobe,
  sync: faGoogleDrive,
  syncUpload: faCloudArrowUp,
  syncHistory: faClock,
  themeDark: faBook,
  themeLight: faBookOpen,
  trends: faWandMagicSparkles,
  upload: faUpload,
  uploadFile: faFileArrowUp,
  userAdd: faUserPlus,
  userCheck: faUserCheck,
  users: faUsers,
  volume: faVolumeHigh,
  audioJobs: faListCheck,
  autoAudio: faVolumeHigh,
  cloud: faCloudArrowUp,
  clock: faClock,
  document: faFileLines,
  moon: faMoon,
  music: faMusic,
  paywall: faTriangleExclamation,
  success: faCheck,
  eye: faEye,
  eyeSlash: faEyeSlash,
} as const satisfies Record<string, IconDefinition>;

interface IconProps extends Omit<FontAwesomeIconProps, 'icon'> {
  icon: IconDefinition;
}

export function Icon({ icon, className, ...props }: IconProps) {
  return <FontAwesomeIcon icon={icon} className={className} {...props} />;
}
